__author__ = 'brandonkelly'

import pymysql

do_not_recommend = \
[
    'angel hair',
    'arborio rice',
    'artichoke heart marin',
    'back ribs',
    'baguette',
    'baking mix',
    'baking powder',
    'baking soda',
    'basmati rice',
    'bass',
    'bean threads',
    'beef',
    'bertolli alfredo sauc',
    'bertolli tomato & basil sauc',
    'biscuits',
    'bisquick',
    'bread',
    'brisket',
    'brown rice',
    'bulk italian sausag',
    'buns',
    'cake',
    'catfish',
    'cheese',
    'cheese slices',
    'cheese soup',
    'chicken',
    'chips',
    'chuck',
    'cod',
    'cooked rice',
    'cooking spray',
    'corn husks',
    'corn starch',
    'cornflour',
    'cornish hens',
    'cornmeal',
    'cream of celery soup',
    'cream of chicken soup',
    'cutlet',
    'dough',
    'dressing',
    'duck',
    'dumpling wrappers',
    'egg noodles, cooked and drained',
    'egg roll wrappers',
    'egg roll wraps',
    'english muffins',
    'essence',
    'fat',
    'fettuccine pasta',
    'fettuccini',
    'filet',
    'filet mignon',
    'fillets',
    'fish',
    'flavoring',
    'florets',
    'flounder',
    'flour',
    'french baguett',
    'french onion soup',
    'frozen mix veget',
    'fryer chickens',
    'gelatin',
    'grating cheese',
    'grits',
    'ground meat',
    'ground round',
    'ground sausage',
    'halibut',
    'hamburger',
    'hominy',
    'hot dog bun',
    'hot dogs',
    'ice',
    'ice cream',
    'italian sauce',
    'jasmine rice',
    'juice',
    'kraft miracle whip dressing',
    'lamb',
    'lasagna noodles',
    'lasagna noodles, cooked and drained',
    'liquid',
    'loin',
    'long-grain rice',
    'macaroni',
    'mahi mahi',
    'manicotti',
    'margarine',
    'marinade',
    'meat',
    'meat tenderizer',
    'meatballs',
    'minute rice',
    'nonstick spray',
    'noodles',
    'oil',
    'orzo',
    'pasta',
    'pasta sauce',
    'pastry',
    'phyllo',
    'pie crust',
    'pie shell',
    'pitas',
    'pizza crust',
    'pizza doughs',
    'pizza sauce',
    'polenta',
    'pork',
    'potato chips',
    'potato starch',
    'prebaked pizza crusts',
    'pretzel stick',
    'processed cheese',
    'quail',
    'ragu pasta sauc',
    'red food coloring',
    'red snapper',
    'refrigerated piecrusts',
    'rib',
    'rice',
    'rice paper',
    'rice sticks',
    'roast',
    'roasting chickens',
    'rolls',
    'round steaks',
    'rub',
    'rump roast',
    'rump steak',
    'salad',
    'salmon',
    'salt',
    'sauce',
    'sausage casings',
    'seasoning',
    'shells',
    'short-grain rice',
    'shortening',
    'sirloin',
    'sole',
    'soup',
    'soup mix',
    'spaghetti, cook and drain',
    'spam',
    'spareribs',
    'spices',
    'spring roll wrappers',
    'steak',
    'steamed rice',
    'stew meat',
    'strip steaks',
    'stuffing mix',
    'sushi rice',
    'sweetener',
    'swordfish',
    'taco shells',
    'textured soy protein',
    'tilapia',
    'toast',
    'tomato soup',
    'tortilla chips',
    'tortillas',
    'trout',
    'tuna',
    'turkey',
    'udon',
    'veal',
    'vegetables',
    'veggies',
    'venison',
    'water',
    'wheat',
    'wheat bread',
    'white rice',
    'whitefish',
    'wide egg noodles',
    'wonton skins',
    'wonton wrappers',
    'yeast',
    'yellow corn meal',

]

merge = \
    [
        ('barbecue sauce', 'barbeque sauce', 'bbq sauce'),
        ('crumbs', 'bread crumbs', 'breadcrumbs'),
        ('beef base', 'beef stock cubes', 'beef bouillon'),
        ('chicken base', 'chicken-flavored soup powder', 'chicken bouillon'),
        ('chile paste', 'chili paste'),
        ('chile paste with garlic', 'chili paste with garlic'),
        ('chile powder', 'ground chile', 'chili powder'),
        ('chili', 'chile pepper', 'chiles'),
        ('chile sauce', 'chili sauce'),
        ('chop fine pecan', 'pecan halves', 'pecans'),
        ('chopped bell pepper', 'bell pepper'),
        ('clove garlic, fine chop', 'garlic'),
        ('coca-cola', 'cola'),
        ('cos', 'leav lettuc romain', 'romaine lettuce'),
        ('crabmeat', 'crab'),
        ('cream cheese, soften', 'cream cheese'),
        ('crimini', 'crimini mushrooms'),
        ('crushed pineapples in juice', 'pineapple'),
        ('curry', 'curry powder'),
        ('diced onions', 'onion'),
        ('dillweed', 'dill'),
        ('dried chile', 'dried chile peppers'),
        ('fresh green bean', 'green beens'),
        ('freshly grated parmesan', 'parmesan cheese', 'parmigiano', 'parmesan'),
        ('frozen broccoli', 'brocolli'),
        ('frozen chopped spinach, thawed and squeezed dry', 'spinach'),
        ('garbonzo', 'chickpeas'),
        ('gingerroot', 'ginger'),
        ('grated carrot', 'carrot'),
        ('green bell pepper, slice', 'green bell pepper'),
        ('green chile', 'green chilies'),
        ('ground cloves', 'whole cloves', 'clove'),
        ('dry mustard', 'ground mustard', 'mustard powder'),
        ('ground sausage', 'sausage'),
        ('ground tumeric', 'tumeric'),
        ('lemon grass', 'lemongrass'),
        ('navel oranges', 'orange'),
        ('oliv pit ripe', 'green olives'),
        ('peel tomato whole', 'tomatoes'),
        ('pepper flakes', 'red pepper flakes'),
        ('evaporated milk', 'powdered milk', 'condensed milk'),
        ('red bell pepper, slice', 'red bell pepper'),
        ('merlot', 'cabernet', 'red wine'),
        ('roast red peppers, drain', 'roasted red peppers'),
        ('sausage links', 'sausages'),
        ('sesame', 'sesame seeds'),
        ('spring onions', 'green onions'),
        ('sundried tomatoes packed in olive oil', 'sun-dried tomatoes'),
        ('uncook medium shrimp, peel and devein', 'shrimp'),
        ('unsalted cashews', 'cashews'),
        ('walnut halves', 'walnut pieces', 'walnuts'),
        ('whipped topping', 'whipped cream'),
        ('whole kernel corn, drain', 'corn'),
        ('yellow bell pepper', 'yellow pepper')
    ]