__author__ = 'brandonkelly'

import pymysql



merge = \
    [
        ('barbecue sauce', 'barbeque sauce', 'bbq sauce'),
        ('crumbs', 'bread crumbs', 'breadcrumbs'),
        ('beef base', 'beef stock cubes', 'beef bouillon'),
        ('chicken base', 'chicken-flavored soup powder', 'chicken bouillon'),
        ('chile paste', 'chili paste'),
        ('chile paste with garlic', 'chili paste with garlic'),
        ('chile powder', 'ground chile', 'chili powder'),
        ('chili', 'chile pepper', 'chiles'),
        ('chile sauce', 'chili sauce'),
        ('chop fine pecan', 'pecan halves', 'pecans'),
        ('chopped bell pepper', 'bell pepper'),
        ('clove garlic, fine chop', 'garlic'),
        ('coca-cola', 'cola'),
        ('cos', 'leav lettuc romain', 'romaine lettuce'),
        ('crabmeat', 'crab'),
        ('cream cheese, soften', 'cream cheese'),
        ('crimini', 'crimini mushrooms'),
        ('crushed pineapples in juice', 'pineapple'),
        ('curry', 'curry powder'),
        ('diced onions', 'onion'),
        ('dillweed', 'dill'),
        ('dried chile', 'dried chile peppers'),
        ('fresh green bean', 'green beens'),
        ('freshly grated parmesan', 'parmesan cheese', 'parmigiano', 'parmesan'),
        ('frozen broccoli', 'brocolli'),
        ('frozen chopped spinach, thawed and squeezed dry', 'spinach'),
        ('garbonzo', 'chickpeas'),
        ('gingerroot', 'ginger'),
        ('grated carrot', 'carrot'),
        ('green bell pepper, slice', 'green bell pepper'),
        ('green chile', 'green chilies'),
        ('ground cloves', 'whole cloves', 'clove'),
        ('dry mustard', 'ground mustard', 'mustard powder'),
        ('ground sausage', 'sausage'),
        ('ground tumeric', 'tumeric'),
        ('lemon grass', 'lemongrass'),
        ('navel oranges', 'orange'),
        ('oliv pit ripe', 'green olives'),
        ('peel tomato whole', 'tomatoes'),
        ('pepper flakes', 'red pepper flakes'),
        ('evaporated milk', 'powdered milk', 'condensed milk'),
        ('red bell pepper, slice', 'red bell pepper'),
        ('merlot', 'cabernet', 'red wine'),
        ('roast red peppers, drain', 'roasted red peppers'),
        ('sausage links', 'sausages'),
        ('sesame', 'sesame seeds'),
        ('spring onions', 'green onions'),
        ('sundried tomatoes packed in olive oil', 'sun-dried tomatoes'),
        ('uncook medium shrimp, peel and devein', 'shrimp'),
        ('unsalted cashews', 'cashews'),
        ('walnut halves', 'walnut pieces', 'walnuts'),
        ('whipped topping', 'whipped cream'),
        ('whole kernel corn, drain', 'corn'),
        ('yellow bell pepper', 'yellow pepper')
    ]